export const USERS_SERVICE = 'USERS_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const PROJECTS_SERVICE = 'PROJECTS_SERVICE';
export const NOTIFICATIONS_SERVICE = 'NOTIFICATIONS_SERVICE';

export const TCP_PORTS = {
  AUTH: 3001,
  USERS: 3002,
  PROJECTS: 3003,
  NOTIFICATIONS: 3006,
};
