export const USERS_SERVICE = 'USERS_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const PROJECTS_SERVICE = 'PROJECTS_SERVICE';
export const NOTIFICATIONS_SERVICE = 'NOTIFICATIONS_SERVICE';

export const TCP_PORTS = {
  AUTH: 3001,
  USERS: 3002,
  PROJECTS: 3003,
  VERIFICATION: 3004,
  NOTIFICATIONS: 3006,
};

export const RMQ_SERVICES = {
  AUTH: 'AUTH_SERVICE_RMQ',
  USERS: 'USERS_SERVICE_RMQ',
  PROJECTS: 'PROJECTS_SERVICE_RMQ',
};

export const RMQ_QUEUES = {
  AUTH: 'auth_queue',
  USERS: 'users_queue',
  PROJECTS: 'projects_queue',
};
